version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: ci
